name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Enable WakaTime plugin
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, languages, editors
          plugin_wakatime_days: 7 # 显示最近 7 天的统计
          # Output settings
          filename: metrics.plugin.wakatime.svg
          base: "" # 禁用默认统计，只生成 WakaTime
          # Theme for light/dark mode
          template: classic
          config_timezone: Asia/Shanghai # 调整为你的时区
          
