name: Update WakaTime Badge

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-wakatime-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.METRICS_TOKEN }} # 使用 METRICS_TOKEN 检出仓库

      - name: Fetch WakaTime stats and generate SVG
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          curl -s -H "Authorization: Basic $(echo -n $WAKATIME_API_KEY | base64)" \
            "https://wakatime.com/api/v1/users/current/stats/all_time" > wakatime_stats.json
          
          TOTAL_TIME=$(jq -r '.data.human_readable_total' wakatime_stats.json)
          
          TOTAL_TIME_ENCODED=$(echo "$TOTAL_TIME" | sed 's/ /%20/g')
          
          curl -s "https://img.shields.io/badge/WakaTime-${TOTAL_TIME_ENCODED}-blue?style=for-the-badge&logo=wakatime" \
            -o assets/wakatime_badge.svg

      - name: Update README
        run: |
          if ! grep -q "![WakaTime Stats](assets/wakatime_badge.svg)" README.md; then
            echo -e "\n## Encoding Statistics\n![WakaTime Stats](assets/wakatime_badge.svg)" >> README.md
          fi

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add assets/wakatime_badge.svg README.md
          git commit -m "Update WakaTime badge" || echo "No changes to commit"
          git push origin main
